version: '3'
name: "microfront"
services:
  auth:
    build:
      context: ./Auth
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Auth:/app

  todo:
    build:
      context: ./Todo-App-Front
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./Todo-App-Front:/app
